export const COMPETITOR_SEEDS = [
  { entityA: 'Aave', entityB: 'Compound', type: 'competes_with' as const },
  { entityA: 'MakerDAO', entityB: 'Aave', type: 'competes_with' as const },
  { entityA: 'Uniswap', entityB: 'SushiSwap', type: 'competes_with' as const },
  { entityA: 'Curve', entityB: 'Balancer', type: 'competes_with' as const },
  { entityA: '1inch', entityB: 'ParaSwap', type: 'competes_with' as const },
  { entityA: 'Lido', entityB: 'Rocket Pool', type: 'competes_with' as const },
  { entityA: 'Chainlink', entityB: 'Band Protocol', type: 'competes_with' as const },
  { entityA: 'OpenSea', entityB: 'Blur', type: 'competes_with' as const },
  { entityA: 'Magic Eden', entityB: 'OpenSea', type: 'competes_with' as const },
  { entityA: 'LooksRare', entityB: 'Blur', type: 'competes_with' as const },
  { entityA: 'dYdX', entityB: 'GMX', type: 'competes_with' as const },
  { entityA: 'Synthetix', entityB: 'dYdX', type: 'competes_with' as const },
  { entityA: 'Arbitrum', entityB: 'Optimism', type: 'competes_with' as const },
  { entityA: 'Polygon', entityB: 'Arbitrum', type: 'competes_with' as const },
  { entityA: 'Base', entityB: 'Arbitrum', type: 'competes_with' as const },
  { entityA: 'zkSync', entityB: 'Starknet', type: 'competes_with' as const },
  { entityA: 'Ethereum', entityB: 'Solana', type: 'competes_with' as const },
  { entityA: 'Bitcoin', entityB: 'Ethereum', type: 'competes_with' as const },
  { entityA: 'Avalanche', entityB: 'Solana', type: 'competes_with' as const },
  { entityA: 'Cosmos', entityB: 'Polkadot', type: 'competes_with' as const },
  { entityA: 'Sui', entityB: 'Aptos', type: 'competes_with' as const },
  { entityA: 'PancakeSwap', entityB: 'Uniswap', type: 'competes_with' as const },
  { entityA: 'Raydium', entityB: 'Orca', type: 'competes_with' as const },
  { entityA: 'Binance', entityB: 'Coinbase', type: 'competes_with' as const },
  { entityA: 'Tether', entityB: 'USDC', type: 'competes_with' as const },
];
